### ISSUE TITLE
Requires grades throws error

### ISSUE THREAD

**Issue by dirkca** [fernandooliveira/moodle-block_marking_manager#10]
![requires-grading](https://cloud.githubusercontent.com/assets/7506068/10078831/03aac65c-62a4-11e5-8be1-f12096a59179.PNG)
Requires grading does not seem to be working. After clicking, the 'Activity Type' and 'Participant' drop downs are not working, ditto for 'Less' and 'More'. When clicking 'Requires Grading' the following error is thrown and displayed via Moodle debugging:

Fatal error: Call to undefined method assign::get_grading_status() in /var/www/moodle/blocks/fn_marking/assign_edit_grade_form.php on line 357

**Comment by mgardener** [comment]
What is your moodle version?

**Comment by fernandooliveira** [comment]
Sorry, forgot to pass along Dirk's details:

Moodle 2.8.1+ (Build: 20141205)
Moodle 2.7+ (Build: 20140626)

**Comment by mgardener** [comment]
Please delete fn_marking folder completely and upload the latest code.

**Comment by dirkca** [comment]
I did. Purged all caches. No luck.

**Comment by fernandooliveira** [comment]
Hi Dirk, can you install the latest code here on GitHub (https://github.com/fernandooliveira/moodle-block_marking_manager/archive/master.zip). Once you verify that it is working properly on your end, I will update the Moodle.org plugin page.  Note that you will have to rename the folder after you download.

**Comment by dirkca** [comment]
Under 'requires Grading' plugin reports assignments that have not been submitted. is that by design?

**Comment by dirkca** [comment]
Plugin reports 8 assignments needing grading. This is what teacher sees.
![requires-grading](https://cloud.githubusercontent.com/assets/7506068/10288376/bd2b5f9c-6b55-11e5-9833-138e9b0d847e.PNG)

**Comment by fernandooliveira** [comment]
I can't seem to reproduce this problem. Can you give me access to a test course that exhibits this issue?
