### ISSUE TITLE
invalidrecord when clicking on requires grading

### ISSUE THREAD

**Issue by timmartinez** [fernandooliveira/moodle-block_marking_manager#11]
In two courses a teacher has, when she clicks on the 'reqires grading' link, she gets the following error:

[06-Oct-2015 11:45:54 America/Denver] Default exception handler: Can not find data record in database table course. Debug: SELECT * FROM {course} WHERE id IS NULL
[array (
)]
Error code: invalidrecord
* line 1451 of \lib\dml\moodle_database.php: dml_missing_record_exception thrown
* line 1427 of \lib\dml\moodle_database.php: call to moodle_database->get_record_select()
* line 588 of \lib\datalib.php: call to moodle_database->get_record()
* line 487 of \lib\grouplib.php: call to get_course()
* line 781 of \lib\grouplib.php: call to groups_get_activity_groupmode()
* line 322 of \blocks\fn_marking\fn_gradebook.php: call to groups_get_activity_group()

FN block version: 2015100100
Moodle Version: 2.8.6+ (20150618)

**Comment by timmartinez** [comment]
Hi,

I upgraded to the latest build and I'm getting the same error.

**Comment by fernandooliveira** [comment]
I can't seem to reproduce this problem. What database system are you using? Can you give me access to a test course that exhibits this issue?

**Comment by fernandooliveira** [comment]
I'm sorry to say that this plugin was not developed for Moodle 2.8. I would suggest upgrading to Moodle 2.9.
