### ISSUE TITLE
Error when trying to access Blogs to rate within the block

### ISSUE THREAD

**Issue by villamizar** [fernandooliveira/moodle-block_marking_manager#12]
Dear Fernando, 

Thank you very much for this useful block.  We have been using it for the last month and all instructors are liking it very much!
The only issue that we have found with the block is that when trying to rate blogs via the block, we get an error (see attached image).  We are able to access all other assignments (quizzes, drop boxes) without any issues.

We are using Moodle 2.9.2+  (Build 20150918)
With a Postgre database v. 9.3.10
FN Marking block:  2015100100

![fn_marking](https://cloud.githubusercontent.com/assets/12071518/10939259/5bf0e626-82ce-11e5-96b5-84d8e9196b06.JPG)

When I enable debugging mode, this is what it displays:

Error reading from database
More information about this error

Debug info: ERROR: column "u.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT u.id as id, u.id AS userid, SUM(r.rating) AS rawgrade
^
SELECT u.id as id, u.id AS userid, SUM(r.rating) AS rawgrade
FROM mdl_user u
LEFT JOIN mdl_forum_posts i
ON u.id=i.userid
LEFT JOIN mdl_rating r
ON r.itemid=i.id
WHERE r.contextid = $1
AND r.component = $2
AND r.ratingarea = $3
AND i.userid = $4
[array (
0 => 299771,
1 => 'mod_forum',
2 => 'post',
3 => '1796',
)]
Error code: dmlreadexception
Stack trace:
line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 764 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 1478 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
line 190 of /blocks/fn_marking/forum.submissions.fn.php: call to moodle_database->get_record_sql()
line 650 of /blocks/fn_marking/fn_gradebook.php: call to include()

Please let me know how I can resolve this issue.  So far what instructors are doing is going to the block to see what blogs need grading, they write them down and then go to the course's main page to grade them.

Have a blessed day,
Sam Villamizar

**Comment by fernandooliveira** [comment]
Hello Sam,

The plugin doesn't handle blogs. Do you mean "forums"? If so, does this happen to all the forums in your site? Also, could you tell me the following:

Moodle version:
Plugin version number:

Thanks,
Fernando
