### ISSUE TITLE
Moodle 3.0: PHP catchable fatal error when saving grade

### ISSUE THREAD

**Issue by FLeone** [fernandooliveira/moodle-block_marking_manager#14]
Thank you for the great plug-in. We just updated to Moodle 3.0 and now the teachers get an PHP catchable fatal error when they try to mark an assignment (right after they click 'save'). Any idea how this can solved?

Thanks a lot in advance!

Frank

**Comment by fernandooliveira** [comment]
Hello Frank. We just finished updating this block to 2.9. There are no plans to upgrade to 3.0 in the immediate future (at least until we come up with some funding).

**Comment by FLeone** [comment]
Good day Fernando,

Thanks for the quick reply. Understandable, we will just look for an
alternative in the mean time.

     best,

             Frank

**Comment by FLeone** [comment]
It seems to work again now, which is good, thanks!

      Frank
