### ISSUE TITLE
Feature request: add support for lessons

### ISSUE THREAD

**Issue by FLeone** [fernandooliveira/moodle-block_marking_manager#16]
Dear supporters,

I really like marking manager, as do the teachers. Currently, the main drawback is that we cannot show lessons with to be graded open questions, while we use them extensively. Could support for them be added? Is this hard? Otherwise, with some pointers, I might be able to do it myself. 

Thanks in advance,

           Frank

**Comment by fernandooliveira** [comment]
Hi Frank,

In this latest version of the Marking Manager, we added the ability to handle quizzes. Now this plug-in handles quizzes, forums and assignments.  When it comes time to develop the next version, we might be able to add the Lesson activity type, but this will depend on cost and available funding. I suspect this will not get done during this school year. If you need this done in the near future, and your school/organization would be willing to pay for this addition, we would be happy to do it. 

Thanks,
Fernando

**Comment by FLeone** [comment]
Dear Fernando,

Thank you for your clear reply. Good to hear the plug-in is still in active development and new features are constantly added. At the moment, we don't have the funds to help you out on this one. But it we have and this functionality remains urgent, we will let you know. 

Good luck with the development of Marking Manager,

      all the best,

              Frank
