### ISSUE TITLE
Block shows courses with no ungraded activities

### ISSUE THREAD

**Issue by FLeone** [fernandooliveira/moodle-block_marking_manager#17]
We have a lot of courses, managed by one and the same teacher. The marking manager helps us out greatly here. However, it does not hide courses where there are no ungraded activities, which means we reach the maximum of 10 courses really soon, and can't see the actually relevant courses. Any pointers on what might be going wrong here?

Thanks in advance,

            Frank

**Comment by fernandooliveira** [comment]
Hello, this has been resolved. The latest release has an option in the block config page to control this behavior: http://screencast.com/t/G2Fzj579WjO4

**Comment by FLeone** [comment]
Hi Fernando,

Thanks a lot, greatly appreciated!

     best,

               Frank
