### ISSUE TITLE
Assignment stays shows "Requires Grading" still after being marked

### ISSUE THREAD

**Issue by dev-brother** [fernandooliveira/moodle-block_marking_manager#18]
Using Moodle 2.9 and fn_marking block

The assignment has already been marked via "Requires Grading". The odd thing is the assignment still stays there even after purging the cache.

**Comment by fernandooliveira** [comment]
We have recently updated the Marking Manager block. This latest version is compatible with Moodle 2.9, 3.0 and 3.1. If you are interested in testing this new version on your site, please give me a shout.
