### ISSUE TITLE
group issues

### ISSUE THREAD

**Issue by sumantaghosh** [fernandooliveira/moodle-block_marking_manager#20]
I know this is not ready yet for Moodle 3.0. Just listing these here to follow it up. 

1)  the block showing total number of quiz "Requires Grading" instead of only from the teacher's group (access all groups permission is set to prevent)
https://goo.gl/photos/hxV1x4oSLVHSzhPL9
2) In the list of Marking status "Requires Grading" the the same thing happens. The number on the left reflects the total number of ungraded assignments from all participants irrespective of any entry for the group the teacher is in. It should not even list that quiz in the first place.
https://goo.gl/photos/AAa5chVq5pQnsfow8

**Comment by fernandooliveira** [comment]
Please retry with latest update.
