### ISSUE TITLE
Sort Simple Gradebook by Last Name

### ISSUE THREAD

**Issue by timmartinez** [fernandooliveira/moodle-block_marking_manager#22]
Right now in the simple gradebook students are listed by first name, initial. (e.g. Smith, J.) and are sorted by Moodle user ID. I was able to get around this by changing line 69 in simple_gradebook.php from:
$simplegradebook[$key]['name'] = $value->firstname.' '.substr($value->lastname,0,1).'.'; 
to:
$simplegradebook[$key]['name'] = $value->lastname.', '.$value->firstname;

Might be useful to build this option into the block configuration.

**Comment by fernandooliveira** [comment]
Thanks. This is fixed.
