### ISSUE TITLE
Errors found using Moodle 3

### ISSUE THREAD

**Issue by yesabc** [fernandooliveira/moodle-block_marking_manager#23]
Hi,

I am using Moodle 3.0.2.  I received a few errors as follow:

1- Notice: Undefined index: numsections in Moodle folder\blocks\ned_marking\fn_gradebook.php on line 283.

2- Notice: Undefined index: news in Moodle folder \blocks\ned_marking\forum.submissions.fn.php on line 146.

3- fn_gradebook.php shows this message: "Coding error detected, it must be fixed by a programmer: PHP catchable fatal error" when I tried to save the new grade for student.

Thank you

**Comment by fernandooliveira** [comment]
Hello, what version of the block are you using?

**Comment by fernandooliveira** [comment]
I am not able to replicate this problem.
