### ISSUE TITLE
Page load problem with FN Marketing

### ISSUE THREAD

**Issue by ruchitvibidsoft** [fernandooliveira/moodle-block_marking_manager#24]
Hello Fernado,

Hope you are doing good. 
I am using block "FN Marking". It is good plugin which meet our requirement.
We are using moodle 3.1 and FN Markeing 2.9 version. We are facing page load problem with this plugin. 
I am attaching two screen shot. One is for course page and another one is for FN Marketing block.
FN Marketing take almost 23 Second each time to load page.

We have already Opcache enabled on server. still it take too much time. Can you please help me out on this?

Regards,
Harshil
![coursepage](https://cloud.githubusercontent.com/assets/20555409/17300001/2a18e46a-582e-11e6-92a0-4b3c05df9784.png)
![fn_marking](https://cloud.githubusercontent.com/assets/20555409/17300002/2a1e913a-582e-11e6-9263-15e3e84457ec.png)

**Comment by fernandooliveira** [comment]
Please try latest version: https://github.com/fernandooliveira/moodle-block_marking_manager/archive/master.zip

**Comment by ruchitvibidsoft** [comment]
I had installed latest code as per your suggestion. I am getting "186 Required Grading" on course page.
But when i clicked on that link it give me "No Selected Assignment".

It was working in older version. But not working in latest version.
![marking](https://cloud.githubusercontent.com/assets/20555409/17456175/4111eda8-5bec-11e6-9b3a-58c59fad4624.png)
![course](https://cloud.githubusercontent.com/assets/20555409/17456176/4116247c-5bec-11e6-890a-4599e2f7a4f3.png)
