### ISSUE TITLE
Problem with grading page. Thread continue from #24

### ISSUE THREAD

**Issue by ruchitvibidsoft** [fernandooliveira/moodle-block_marking_manager#25]
I had installed latest code as per your suggestion. I am getting "186 Required Grading" on course page.
But when i clicked on that link it give me "No Selected Assignment".

It was working in older version. But not wor
![course](https://cloud.githubusercontent.com/assets/20555409/17456187/75f9afba-5bec-11e6-98a6-4c5d3a0968b1.png)
![marking](https://cloud.githubusercontent.com/assets/20555409/17456188/788211e6-5bec-11e6-8e4b-ea84a4b2ebfb.png)

king in latest version.

**Comment by fernandooliveira** [comment]
What version of Moodle are you using?

**Comment by ruchitvibidsoft** [comment]
I am using Moodle Version 2016052300.00
3.1 (Build: 20160523)

I got the problem and fixed.
I am using "flexsections" in course format type. 
"numsections" is missing in fn_gradebook.php file

I added code around line 305
// FIND CURRENT WEEK.
$courseformatoptions = course_get_format($course)->get_format_options();
$courseformat = course_get_format($course)->get_format();
$coursenumsections = $courseformatoptions['numsections'];
if ( isset($courseformatoptions['numsections'])) {
	$coursenumsections = $courseformatoptions['numsections'];
} else {
	$coursenumsections = 10; // Default section number.
}

and it works for me.

**Comment by fernandooliveira** [comment]
Thanks. This has been added to the code.
