### ISSUE TITLE
Courses with 0 ungraded items in front page mode

### ISSUE THREAD

**Issue by Syxton** [fernandooliveira/moodle-block_marking_manager#27]
I'm getting a lot of courses that don't have ungraded assignments show up in the list.  Is this the intended result?

**Comment by fernandooliveira** [comment]
Can you check this setting: http://screencast.com/t/lUcyJSzvs

**Comment by Syxton** [comment]
@fernandooliveira it is set as shown

**Comment by Syxton** [comment]
@fernandooliveira Interesting information, the default was "No".  After setting it to "Yes" and seeing the same results, I set it BACK to "No" and now it works as expected.  So the issue exists because the default setting isn't being enforced.

**Comment by fernandooliveira** [comment]
Thanks for reporting.
