### ISSUE TITLE
NED says I have unmarked Forum posts, but I don't

### ISSUE THREAD

**Issue by tofinosurfer** [fernandooliveira/moodle-block_marking_manager#28]
Over time, most - if not all - of my Forums are listed by NED as having 1 unmarked Forum post. But they are all marked. This eventually affects all the forums so that after a few months, all of the forums supposedly have one unmarked post. And whenever somebody actually does post to the forum, it still says 1 unmarked, therefore once or twice per week I need to go through all the forums to check what the situation actually is. 

Using NED Version: 2016092700 on Moodle 3.1.1+ (Build: 20160901)

**Comment by fernandooliveira** [comment]
Thanks for your post. Please update to latest version to see if this resolves your problem.

**Comment by tofinosurfer** [comment]
So I installed the new version, and when I added the NED Block, it announced that I had six unmarked forum posts. I double checked each forum, and every forum is fully marked.

**Comment by tofinosurfer** [comment]
Is there some other step I should be taking?

**Comment by fernandooliveira** [comment]
Hi, I could not replicate this problem. Do you have a test site I could access?

**Comment by tofinosurfer** [comment]
The challenge is that I need a number of forum posts from different uses for the issue to appear. I might be able to create a new Moodle site, and then have a bunch of students sign up with fake names and start posting to a forum until the issue appears. I can then give you full admin/server access to that site. I'll get back to you. P.S. In my opinion, the NED marking block is one of the best things to happen to Moodle in ages. Thank you for your work on this.

**Comment by tofinosurfer** [comment]
Okay, I'm ready. I created a test site (latest Moodle and latest NED) with dummy user accounts and created two forums and made posts from a few of the users. And now, NED says I have 1 post to mark, yet the posts are all marked. Should I create an admin account for you and send login credentials? Or do you need server file access?

**Comment by tofinosurfer** [comment]
I've sent you admin login credentials to my test site. Thanks for looking into this. Glen.

**Comment by fernandooliveira** [comment]
Thanks. I'm looking into it.

**Comment by fernandooliveira** [comment]
Hi, are you able to send me access to mysql too?

**Comment by tofinosurfer** [comment]
Done.

**Comment by tofinosurfer** [comment]
I've switched hosts, and the test site didn't carry over to the new server. Should I set up another test site?

**Comment by tofinosurfer** [comment]
I've tracked it down. The bug only occurs when I (admin and student in the class) reply to a post. My guess is that because I enrolled myself in the course (rookie mistake - because I thought I had to), any post I make looks like it came from a student, and therefore needs to be marked.  I'll unenroll as a student and see if that fixes it.

**Comment by tofinosurfer** [comment]
Yup, that fixes it. Thanks for your time on this one. Glen.
