### ISSUE TITLE
Cron is giving me Trying to get property of non-object in /var/www/moodle/blocks/fn_marking/lib.php on line 688

### ISSUE THREAD

**Issue by Syxton** [fernandooliveira/moodle-block_marking_manager#29]
Error happens over and over on this line:

if (!isset($modgradesarray[$mod->modname])) {

**Comment by fernandooliveira** [comment]
Please provide more info:

Moodle version
Plugin version
Database type

**Comment by Syxton** [comment]
@fernandooliveira Sorry
Moodle 3.1.3+ (Build: 20161115)
Plugin version 3.1.4 (2016110400)
MariaDB

**Comment by Syxton** [comment]
Also, I quoted the same line from the latest git, but our actual plugin code running says: 
PHP Notice:  Trying to get property of non-object in /var/www/moodle/blocks/fn_marking/lib.php on line 651

**Comment by fernandooliveira** [comment]
Can you try updating to latest code here: https://github.com/fernandooliveira/moodle-block_marking_manager
