### ISSUE TITLE
Layout issue with online text

### ISSUE THREAD

**Issue by Syxton** [fernandooliveira/moodle-block_marking_manager#30]
![layout issue](https://cloud.githubusercontent.com/assets/989354/20927508/f2c96ea6-bb8f-11e6-80bb-38869cedca5b.png)
![code](https://cloud.githubusercontent.com/assets/989354/20927507/f2c8525a-bb8f-11e6-9860-8ba514c64bae.png)

the "fn_plugin_wrapper_outer" is floated so it falls beneath "fitem_id_onlinetext".  "fitemtitle" also is floated so it pushes the editor icons more to the right as well

**Comment by Syxton** [comment]
This is running the 2016113000 version of NED on Moodle 3.1

**Comment by Syxton** [comment]
Happens if both file and onlinetext submissions are enabled

**Comment by Syxton** [comment]
wrapping the fn_plugin_wrapper_outer" divs with a div that is "display:inline-block; width:100%" fixes that part.  Same for the fitemtitle

**Comment by Syxton** [comment]
in the fn_marking styles.css I made the following modification and it fixed the issue: changed .fn_plugin_wrapper_outer to display: inline-block instead of float. and then added a piece to hide the fitemtitle

.fn_plugin_wrapper_outer {
    display: inline-block;
    margin: 10px auto;
    width: 50%;
}
table.markingmanagercontainer div.fitemtitle {
    display: none;
}

**Comment by fernandooliveira** [comment]
Thanks for the code! This is fixed.
