### ISSUE TITLE
Maximum Grade not Showing

### ISSUE THREAD

**Issue by mkrintoul** [fernandooliveira/moodle-block_marking_manager#32]
For assignments that use the Grade Type “Point”, the maximum grade does not show in the Marking Manager. You are given the box in which to type the grade, but not information for what the grade is out of. This means that you have to open the assignment to see the maximum grade before you can assign a grade in the Marking Manager, which defeats the point of using it. I can’t find any place where this might be configurable to show/hide. 
![mmerror](https://cloud.githubusercontent.com/assets/25039954/21820864/4139e0be-d726-11e6-870a-9762d9acac1f.png)

**Comment by fernandooliveira** [comment]
This issue has been fixed with latest release.
