### ISSUE TITLE
utf8mb4 encoding causes install issues

### ISSUE THREAD

**Issue by Syxton** [fernandooliveira/moodle-block_marking_manager#33]
Moodle will begin to recommend utf8mb4 in upcoming versions.  https://tracker.moodle.org/browse/MDL-54901

I've recently attempted to install fn_marking_manager on a new 3.3 running with utf8mb4 collation.  It will not install because of the ix_cor_mod_us unique key being too many bytes.  Keys have a maximum of 191 characters, or 764 bytes.

**Comment by fernandooliveira** [comment]
A fix has been uploaded. Please test.
