### ISSUE TITLE
Not yet graded quiz shows in graded group

### ISSUE THREAD

**Issue by shatami** [fernandooliveira/moodle-block_marking_manager#36]
In the plugin, not-yet-graded quiz is in the graded group instead of require grading. However, this quiz has some questions requires manual grading and allows 2 attempts. Also, I need to check "show all participants" box to show this attempt in the view.
![marking manager 1](https://cloud.githubusercontent.com/assets/23088147/26474959/4f334478-4169-11e7-9f65-3a913018ae9f.jpeg)

**Comment by fernandooliveira** [comment]
Would you be able to email me login details a link to the course that has this problem?

**Comment by fernandooliveira** [comment]
Hello, this issue has been fixed in latest version, which can be found here: https://moodle.org/plugins/block_fn_marking
