### ISSUE TITLE
ALERT INACCURATE: 10 Students have not submitted any activities for 7 days

### ISSUE THREAD

**Issue by schalkvn** [fernandooliveira/moodle-block_marking_manager#38]
This Alert is Inaccurate: "10 Students have not submitted any activities for 7 days"

Marking Manager shows the ALERT as follows:
![screen shot 2017-07-30 at 10 11 31 am](https://user-images.githubusercontent.com/30025756/28754674-8a208d14-750f-11e7-9c51-0486774d2a21.png)

List of 10 Students who are reported not to have any Activities submitted during the last 7 days
![screen shot 2017-07-30 at 10 09 25 am](https://user-images.githubusercontent.com/30025756/28754689-22f51276-7510-11e7-8195-5fef365ad9fb.png)

Example for Title of Assignment with submissions during the last 7 days
![screen shot 2017-07-30 at 10 09 51 am](https://user-images.githubusercontent.com/30025756/28754684-ec46f384-750f-11e7-8331-e2c002b28423.png)

List of submissions during the last 7 days of the Assignment used as an Example
![screen shot 2017-07-30 at 10 08 54 am](https://user-images.githubusercontent.com/30025756/28754698-6b8589e4-7510-11e7-809e-a2011267d62c.png)

Please advise urgently - Students are confused

**Comment by fernandooliveira** [comment]
Can you check to see that the Moodle cron job is running on your site? Not sure if this is a bug or a problem on your site, but you may want to turn off this notification for now to prevent confusion with your students.

**Comment by schalkvn** [comment]
Problem still exists.

- I checked that the cron job is running daily
- We are running Moodle 3.2.2+ (Build: 20170324)
- Notification turned off for now

Thanks,
Schalk van Niekerk

**Comment by fernandooliveira** [comment]
this has been fixed
