### ISSUE TITLE
Work to be graded not showing on teacher's dashboard or home page

### ISSUE THREAD

**Issue by danahsm** [fernandooliveira/moodle-block_marking_manager#39]
Work to be graded shows on administrator's home page, but will not show on teacher's home page. 
Moodle 3.1, Marking manager 3.2.1. Have added block to teacher's page, the block is there it just isn't showing any thing to be graded that is attached to them (via a group). Have run cron.

**Comment by fernandooliveira** [comment]
Hi, When you say "teacher's page", I assume you mean the Dashboard? If so, I can't replicate this problem. If you want to send me login details, I'd be happy to take a look.

**Comment by fernandooliveira** [comment]
Please try latest code from Github

**Comment by senaiboy** [comment]
Having the same issue with this. Block is showing on frontpage when logged in as administrator, but not showing on teacher's frontpage.

Using Moodle 3.4, Marking Manager 3.3.2. Cron has been run as well.
