### ISSUE TITLE
PHP Notice:  Undefined index: numsections in /data/www/moodle/moodle/blocks/fn_marking/fn_gradebook.php on line 363

### ISSUE THREAD

**Issue by bradhowe** [fernandooliveira/moodle-block_marking_manager#40]
Hi Fernando,
We have another that has presented itself.
Not sure why a lot of the notifications for NED marking aren't registering... 
I am debugging locally but hoped you may have some insight.

Moodle  - Moodle 3.3.1+ (Build: 20170901)
Marking Manager - block_fn_marking  - 3.3.1 2017083001 

[Fri Sep 29 00:26:33.687442 2017] [php7:notice] [pid 19916:tid 140215607830272] [client 02.166.250:53272] PHP Notice:  Undefined index: numsections in /data/www/moodle/moodle/blocks/fn_marking/fn_gradebook.php on line 363, referer: http://moodle.ca/blocks/fn_marking/fn_gradebook.php

[Fri Sep 29 00:28:00.243111 2017] [php7:notice] [pid 30748:tid 140215691757312] [client 99.19.19:49367] PHP Notice:  Undefined index: numsections in /data/www/moodle/moodle/blocks/fn_marking/fn_gradebook.php on line 363, referer: http://moodle.ca/grade/report/grader/index.php?id=851

**Comment by fernandooliveira** [comment]
Thanks. We are working on a fix.

**Comment by bradhowe** [comment]
That's great to hear, if you need any help or logs, let me know

**Comment by bradhowe** [comment]
Hi team, has there been any update or progress on this issue? Users are beginning to lose faith in the plugin. Is there anything I can do to help expedite the resolution

**Comment by fernandooliveira** [comment]
Hi Brad, Sorry for the delay but the changes that we're working on run pretty deep. Hope to have it ready soon.

**Comment by fernandooliveira** [comment]
Hi Brad, please try latest code. Thanks.

**Comment by fernandooliveira** [comment]
The latest version is now available on the Moodle site https://moodle.org/plugins/block_fn_marking
