### ISSUE TITLE
Work not showing

### ISSUE THREAD

**Issue by tofinosurfer** [fernandooliveira/moodle-block_marking_manager#42]
After updating to the latest NED Marking Manager, no work is showing that needs marking. I am running Moodle 3.3.1+ (20170824). I'm using Mac OS 10.12.5. Chrome Browser.

**Comment by fernandooliveira** [comment]
Can you check to make sure the courses are selected here https://www.screencast.com/t/dBXQMooAWL

**Comment by tofinosurfer** [comment]
I checked that setting, and selected the courses and saved the settings. Yet after that, under "Course categories included", nothing is listed ("Default: None" is greyed out). Should any courses or categories be listed there? Do I need to do anything else after that? Run cron, etc.

**Comment by tofinosurfer** [comment]
**Problem solved** when I added the Marking Block to individual course pages.
