### ISSUE TITLE
Progress Report page displays all groups despite "separate group" being set to Yes

### ISSUE THREAD

**Issue by senaiboy** [fernandooliveira/moodle-block_marking_manager#44]
The course's "Separate groups" setting has been set to yes, so that a teacher cannot see another teacher's students. When viewing Gradebook or Student List, it is working as intended and the teacher can only see his/her own students (who are in the same group as the teacher)

However, when viewing the Progress Report page, the teacher is able to view all students including those from other groups.

**Comment by fernandooliveira** [comment]
I can't reproduce this problem. What version of Moodle are you using? Also, are you using the latest code located on GitHub?
